### ISSUE TITLE
Next/Previous/Finish buttons should have correct spacing

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-progress-indicator#33]
### Expected behavior

Next / Previous / Finish Buttons should have correct spacing

### Actual behavior

Next / Previous / Finish Buttons do not have correct spacing (right next to each other)

![image](https://user-images.githubusercontent.com/5076129/70550767-ea87a500-1b3b-11ea-82b2-e33bc4304ce5.png)

**Comment by Blackbaud-IsaacAggrey** [comment]
There is a selector for `.sky-btn` siblings that exist in a modal footer here: https://github.com/blackbaud/skyux-modals/blob/263f2aff682a278a412d272b4fe60a33f44188cf/src/app/public/modules/modal/modal.component.scss#L125

```css

.sky-modal-footer {
 
   //...other stuff

  ::ng-deep .sky-btn + .sky-btn {
    margin-left: $sky-margin;
  }
}
```

...but it doesn't apply within the way the progress indicator nav buttons are adjacent siblings instead of the buttons.
